#!/bin/sh

PIDFile=$(pwd)/test.pid
User=$USER
WorkingDirectory=./
my_test_service=sleep
ExecStart="/bin/sleep 100"
LOGDIR=./
NEWSERVNAME="test"


#/sbin/start-stop-daemon --start --exec /bin/su --pidfile $PIDFile --make-pidfile --user $User -- -s /bin/sh -l $User -c "cd $WorkingDirectory ; exec $ExecStart &" &> $LOGDIR/$NEWSERVNAME.log
#/sbin/start-stop-daemon --start --exec /bin/su --pidfile $PIDFile --make-pidfile -b --user $User -- -s /bin/sh -l $User -c "cd $WorkingDirectory ; exec $ExecStart &" &> $LOGDIR/$NEWSERVNAME.log

/sbin/start-stop-daemon --start --pidfile $PIDFile --make-pidfile --background --user $User --startas "$ExecStart" &> $LOGDIR/$NEWSERVNAME.log


realpid=$(ps aux | grep -v grep | grep -m1 ".*${my_test_service}")

cat $PIDFile
echo $realpid