#!/bin/sh

myuser="my.user"
mypid="my.pid"
mydir="my.dir"
myhome="my.home"

echo "Started"

echo $(whoami) > $myuser
echo $$ > $mypid
echo $(pwd) > $mydir
echo $HOME > $myhome
id -u > my.id

echo "second $1"

exec sleep 20

#After exec not run
#rm -rf $1
# $myuser $mypid $mydir $myhome