#!/bin/sh

mkdir $1 || exit

cd $1 || exit

myuser="my.user"
mypid="my.pid"
mydir="my.dir"
myhome="my.home"

echo "Started"

echo $(whoami) > $myuser
echo $$ > $mypid
echo $(pwd) > $mydir
echo $HOME > $myhome
id -u > my.id
sleep 20

rm -rf $1
# $myuser $mypid $mydir $myhome