#!/bin/sh


mkdir $1

cd $1

myuser="my.user"
mypid="my.pid"
mydir="my.dir"
myhome="my.home"

echo "Started"

echo $(whoami) > $myuser
echo $$ > $mypid
echo $(pwd) > $mydir
echo $HOME > $myhome
sleep 20

#rm -f $myuser $mypid $mydir $myhome